#!/usr/bin/env python3
import sys

if len(sys.argv) < 4:
    print("Usage: embed.py <input_bin> <output_header> <array_name>")
    sys.exit(1)

input_bin = sys.argv[1]
output_header = sys.argv[2]
array_name = sys.argv[3]

with open(input_bin, "rb") as f:
    data = f.read()

with open(output_header, "w") as f:
    f.write("// Auto-generated by embed.py\n")
    f.write("#pragma once\n")
    f.write("#include <stdint.h>\n")
    f.write("#include <stddef.h>\n")
    f.write("const uint8_t " + array_name + "[] = {\n    ")

    for i, byte in enumerate(data):
        f.write(f"0x{byte:02x}, ")
        if (i + 1) % 12 == 0:
            f.write("\n    ")

    f.write("\n};\n")
    f.write("const size_t " + array_name + "_size = sizeof(" + array_name + ");\n")
