// SPDX-License-Identifier: MIT
#pragma once
#include <stdint.h>

#define TRACED_SNAPSHOT_PATH "/run/trace.snapshot"
#define TRACED_PRODUCER_NAME_MAX 16u

#define TRACED_PRODUCER_CATEGORY_GENERIC 0u
#define TRACED_PRODUCER_CATEGORY_SERVICE 1u
#define TRACED_PRODUCER_CATEGORY_DRIVER  2u
#define TRACED_PRODUCER_CATEGORY_APP     3u

#define TRACED_MSG_START_SESSION 1u
#define TRACED_MSG_STOP_SESSION  2u
#define TRACED_MSG_RESET_SESSION 3u
#define TRACED_MSG_GET_INFO      4u
#define TRACED_MSG_GET_COUNTERS  5u
#define TRACED_MSG_CAPTURE_SNAPSHOT 6u
#define TRACED_MSG_GET_SESSION   7u
#define TRACED_MSG_REGISTER_PRODUCER 8u
#define TRACED_MSG_CONTROL_REPLY 9u
#define TRACED_MSG_INFO_REPLY    10u
#define TRACED_MSG_COUNTERS_REPLY 11u
#define TRACED_MSG_SNAPSHOT_REPLY 12u
#define TRACED_MSG_SESSION_REPLY 13u
#define TRACED_MSG_PRODUCER_REPLY 14u
#define TRACED_MSG_GET_PRODUCER 15u
#define TRACED_MSG_PRODUCER_INFO_REPLY 16u
#define TRACED_MSG_CAPTURE_EXPORT 17u
#define TRACED_MSG_EXPORT_REPLY 18u

#define TRACED_MSG_ENABLE  TRACED_MSG_START_SESSION
#define TRACED_MSG_DISABLE TRACED_MSG_STOP_SESSION
#define TRACED_MSG_RESET   TRACED_MSG_RESET_SESSION

#define TRACED_CTL_OK    0u
#define TRACED_CTL_EFAIL 1u
