#!/usr/bin/env python3
# SPDX-License-Identifier: MIT

from __future__ import annotations

import sys
from pathlib import Path

import product_info


def require_mapping(value: object, label: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise RuntimeError(f"missing mapping: {label}")
    return value


def require_int(value: object, label: str) -> int:
    if isinstance(value, int):
        return value
    if isinstance(value, str) and value:
        try:
            return int(value, 0)
        except ValueError as error:
            raise RuntimeError(f"invalid integer for {label}: {value}") from error
    raise RuntimeError(f"missing integer: {label}")


def emit_hex(value: int) -> str:
    return f"0x{value:X}"


def resolve_board(product_name: str) -> dict[str, int]:
    data = product_info.resolved_manifest(product_name)
    arch = data.get("arch")
    if arch != "armv7":
        raise RuntimeError(f"product '{product_name}' is not an armv7 product")

    board = require_mapping(data.get("board"), "board")
    platform = require_mapping(board.get("platform"), "board.platform")
    uart = require_mapping(platform.get("uart"), "board.platform.uart")
    gic = require_mapping(platform.get("gic"), "board.platform.gic")
    timer = require_mapping(platform.get("timer"), "board.platform.timer")
    memory = require_mapping(platform.get("memory"), "board.platform.memory")
    psci = require_mapping(platform.get("psci"), "board.platform.psci")
    power = require_mapping(platform.get("power"), "board.platform.power")
    conduit = psci.get("conduit")
    if conduit == "hvc":
        psci_conduit = 1
    elif conduit == "smc":
        psci_conduit = 0
    else:
        raise RuntimeError(f"unsupported PSCI conduit: {conduit}")
    shutdown_method = power.get("shutdown_method")
    if shutdown_method == "semihost":
        power_shutdown_method = 1
    elif shutdown_method == "psci":
        power_shutdown_method = 0
    else:
        raise RuntimeError(f"unsupported shutdown method: {shutdown_method}")

    return {
        "uart_base": require_int(uart.get("base"), "board.platform.uart.base"),
        "uart_fr_offset": require_int(uart.get("fr_offset"), "board.platform.uart.fr_offset"),
        "uart_tx_full_mask": require_int(
            uart.get("tx_full_mask"), "board.platform.uart.tx_full_mask"
        ),
        "gic_dist_base": require_int(gic.get("dist_base"), "board.platform.gic.dist_base"),
        "gic_cpu_base": require_int(gic.get("cpu_base"), "board.platform.gic.cpu_base"),
        "timer_irq": require_int(timer.get("irq"), "board.platform.timer.irq"),
        "cpu_count": require_int(platform.get("cpu_count"), "board.platform.cpu_count"),
        "ram_base": require_int(memory.get("ram_base"), "board.platform.memory.ram_base"),
        "ram_size": require_int(memory.get("ram_size"), "board.platform.memory.ram_size"),
        "kernel_load_address": require_int(
            memory.get("kernel_load_address"),
            "board.platform.memory.kernel_load_address",
        ),
        "psci_conduit": psci_conduit,
        "power_shutdown_method": power_shutdown_method,
    }


def write_header(path: Path, values: dict[str, int]) -> None:
    with path.open("w", encoding="utf-8") as out:
        out.write("// SPDX-License-Identifier: MIT\n")
        out.write("// Auto-generated by generate_arm_board_support.py\n")
        out.write("#pragma once\n")
        out.write("#include <stdint.h>\n\n")
        out.write("namespace arch::armv7::platform {\n")
        out.write(
            f"inline constexpr uintptr_t UART_BASE = {emit_hex(values['uart_base'])}UL;\n"
        )
        out.write(
            f"inline constexpr uintptr_t UART_FR_OFFSET = {emit_hex(values['uart_fr_offset'])}UL;\n"
        )
        out.write(
            f"inline constexpr uint32_t UART_TX_FULL_MASK = {emit_hex(values['uart_tx_full_mask'])}U;\n"
        )
        out.write(
            f"inline constexpr uintptr_t GIC_DIST_BASE = {emit_hex(values['gic_dist_base'])}UL;\n"
        )
        out.write(
            f"inline constexpr uintptr_t GIC_CPU_BASE = {emit_hex(values['gic_cpu_base'])}UL;\n"
        )
        out.write(
            f"inline constexpr uint32_t TIMER_IRQ = {emit_hex(values['timer_irq'])}U;\n"
        )
        out.write(
            f"inline constexpr uint32_t CPU_COUNT = {values['cpu_count']}U;\n"
        )
        out.write(
            f"inline constexpr uintptr_t RAM_BASE = {emit_hex(values['ram_base'])}UL;\n"
        )
        out.write(
            f"inline constexpr uintptr_t RAM_SIZE = {emit_hex(values['ram_size'])}UL;\n"
        )
        out.write(
            f"inline constexpr uintptr_t KERNEL_LOAD_ADDRESS = {emit_hex(values['kernel_load_address'])}UL;\n"
        )
        out.write(
            f"inline constexpr uint32_t PSCI_CONDUIT = {values['psci_conduit']}U;\n"
        )
        out.write(
            f"inline constexpr uint32_t POWER_SHUTDOWN_METHOD = {values['power_shutdown_method']}U;\n"
        )
        out.write("} // namespace arch::armv7::platform\n")


def write_linker_script(path: Path, values: dict[str, int]) -> None:
    with path.open("w", encoding="utf-8") as out:
        out.write("/* SPDX-License-Identifier: MIT */\n")
        out.write("ENTRY(_start)\n\n")
        out.write("SECTIONS {\n")
        out.write(f"    . = {emit_hex(values['kernel_load_address'])};\n\n")
        out.write("    .text : ALIGN(4K) {\n")
        out.write("        KEEP(*(.vectors))\n")
        out.write("        KEEP(*(.text.boot))\n")
        out.write("        *(.text*)\n")
        out.write("    }\n\n")
        out.write("    .rodata : ALIGN(4K) {\n")
        out.write("        *(.rodata*)\n")
        out.write("    }\n\n")
        out.write("    .data : ALIGN(4K) {\n")
        out.write("        *(.data*)\n")
        out.write("    }\n\n")
        out.write("    .bss : ALIGN(4K) {\n")
        out.write("        __bss_start = .;\n")
        out.write("        *(COMMON)\n")
        out.write("        *(.bss*)\n")
        out.write("        __bss_end = .;\n")
        out.write("    }\n\n")
        out.write("    . = ALIGN(4K);\n")
        out.write("    kernel_end = .;\n")
        out.write("}\n")


def main() -> int:
    if len(sys.argv) != 4:
        print(
            "Usage: generate_arm_board_support.py <header> <linker_script> <product>",
            file=sys.stderr,
        )
        return 1

    header_path = Path(sys.argv[1])
    linker_path = Path(sys.argv[2])
    product_name = sys.argv[3]

    try:
        values = resolve_board(product_name)
        write_header(header_path, values)
        write_linker_script(linker_path, values)
    except Exception as error:  # noqa: BLE001
        print(f"error: {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
