#!/usr/bin/env python3
# SPDX-License-Identifier: MIT

from __future__ import annotations

import sys
from pathlib import Path
from typing import TypedDict

import product_info

REPO_ROOT = Path(__file__).resolve().parent.parent


class ServicePolicy(TypedDict, total=False):
    autostart: bool
    restart_on_failure: bool
    restart_on_success: bool
    max_restart_attempts: int
    restart_delay_ms: int
    dependencies: list[str]


SERVICE_POLICIES: dict[str, ServicePolicy] = {
    "console": {
        "autostart": True,
        "restart_on_failure": True,
        "max_restart_attempts": 8,
        "restart_delay_ms": 250,
        "dependencies": [],
    },
    "traced": {
        "autostart": True,
        "restart_on_failure": True,
        "max_restart_attempts": 8,
        "restart_delay_ms": 250,
        "dependencies": ["console"],
    },
    "logd": {
        "autostart": True,
        "restart_on_failure": True,
        "max_restart_attempts": 8,
        "restart_delay_ms": 250,
        "dependencies": ["console"],
    },
    "net": {
        "autostart": True,
        "restart_on_failure": True,
        "max_restart_attempts": 8,
        "restart_delay_ms": 250,
        "dependencies": ["console"],
    },
    "kbd": {
        "autostart": True,
        "restart_on_failure": True,
        "max_restart_attempts": 8,
        "restart_delay_ms": 250,
        "dependencies": ["console"],
    },
    "sh": {
        "restart_on_success": True,
        "autostart": True,
        "restart_on_failure": True,
        "max_restart_attempts": 8,
        "restart_delay_ms": 250,
        "dependencies": ["console"],
    },
    "rtorrent": {
        "autostart": False,
        "restart_on_failure": False,
        "max_restart_attempts": 0,
        "restart_delay_ms": 0,
        "dependencies": ["net", "console"],
    },
    "trace": {
        "autostart": False,
        "restart_on_failure": False,
        "max_restart_attempts": 0,
        "restart_delay_ms": 0,
        "dependencies": ["traced", "console"],
    },
    "dmesg_smoke": {
        "autostart": True,
        "restart_on_failure": False,
        "max_restart_attempts": 0,
        "restart_delay_ms": 0,
        "dependencies": ["logd", "console"],
    },
    "cred_smoke": {
        "autostart": True,
        "restart_on_failure": False,
        "max_restart_attempts": 0,
        "restart_delay_ms": 0,
        "dependencies": ["console"],
    },
    "gui_smoke": {
        "autostart": True,
        "restart_on_failure": False,
        "max_restart_attempts": 0,
        "restart_delay_ms": 0,
        "dependencies": ["console"],
    },
    "unixsock_smoke": {
        "autostart": True,
        "restart_on_failure": False,
        "max_restart_attempts": 0,
        "restart_delay_ms": 0,
        "dependencies": ["console"],
    },
    "poweroff_smoke": {
        "autostart": True,
        "restart_on_failure": False,
        "max_restart_attempts": 0,
        "restart_delay_ms": 0,
        "dependencies": ["console", "logd"],
    },
    "reboot_smoke": {
        "autostart": True,
        "restart_on_failure": False,
        "max_restart_attempts": 0,
        "restart_delay_ms": 0,
        "dependencies": ["console", "logd"],
    },
    "wm": {
        "autostart": True,
        "restart_on_failure": False,
        "max_restart_attempts": 0,
        "restart_delay_ms": 0,
        "dependencies": ["console"],
    },
    "wm_client": {
        "autostart": True,
        "restart_on_failure": False,
        "max_restart_attempts": 0,
        "restart_delay_ms": 0,
        "dependencies": ["wm", "console"],
    },
}


def normalize_list(value: object) -> list[str]:
    if isinstance(value, list):
        return [str(item) for item in value]
    return []


def resolve_product(product_name: str) -> tuple[list[str], list[str], list[str]]:
    data = product_info.resolved_manifest(product_name)
    product = data.get("product")
    if not isinstance(product, dict):
        raise RuntimeError("invalid product manifest")

    services = normalize_list(product.get("services"))
    programs = normalize_list(product.get("programs"))
    apps = services + [program for program in programs if program not in services]

    import re

    for app in apps:
        if not re.fullmatch(r"[a-z][a-z0-9_]*", app):
            raise RuntimeError(f"invalid application name: {app}")

    return services, programs, apps


def write_embedded_header(path: Path, apps: list[str]) -> None:
    with path.open("w", encoding="utf-8") as out:
        out.write("// SPDX-License-Identifier: MIT\n")
        out.write("// Auto-generated by generate_product_headers.py\n")
        out.write("#pragma once\n")
        out.write("#include <kernel/process/spawn.hpp>\n")
        out.write("#include <kernel/vfs/ramfs.hpp>\n")
        out.write("\n")
        for app in apps:
            out.write(f"#include <{app}_bin.hpp>\n")
        out.write("\n")
        out.write("namespace kernel::boot {\n")
        out.write("\n")
        out.write("inline void populate_embedded_binaries(kernel::vfs::vfs_node* bin) {\n")
        for app in apps:
            out.write(f'    kernel::vfs::ramfs::create_file(bin, "{app}", {app}_bin, {app}_bin_size);\n')
        out.write("}\n")
        out.write("\n")
        out.write("inline void start_initial_processes() {\n")
        initial = ["init"] if "init" in apps else apps
        for app in initial:
            tid = 1 if app == "init" else 0
            out.write(f'    kernel::process::spawn_path("/bin/{app}", {tid});\n')
        out.write("}\n")
        out.write("} // namespace kernel::boot\n")


def cpp_bool(value: bool) -> str:
    return "true" if value else "false"


def dependency_slots(dependencies: list[str]) -> tuple[list[str], int]:
    if len(dependencies) > 3:
        raise RuntimeError("service policy exceeds MAX_SERVICE_DEPS")
    slots = [f'"{dep}"' for dep in dependencies]
    while len(slots) < 3:
        slots.append("nullptr")
    return slots, len(dependencies)


def write_init_config_header(path: Path, services: list[str], programs: list[str]) -> None:
    selected = services + [program for program in programs if program not in services]
    managed = [app for app in selected if app != "init" and app in SERVICE_POLICIES]

    with path.open("w", encoding="utf-8") as out:
        out.write("// SPDX-License-Identifier: MIT\n")
        out.write("// Auto-generated by generate_product_headers.py\n")
        out.write("#pragma once\n")
        out.write("\n")
        out.write(f"static constexpr unsigned k_service_config_count = {len(managed)};\n")
        out.write(f"static constexpr service_config k_service_configs[{max(1, len(managed))}] = {{\n")
        for app in managed:
            policy = SERVICE_POLICIES[app]
            deps, dep_count = dependency_slots(list(policy["dependencies"]))
            out.write(
                f'    {{"{app}", "/bin/{app}", {cpp_bool(bool(policy["autostart"]))}, '
                f"{cpp_bool(bool(policy['restart_on_failure']))}, "
                f"{cpp_bool(bool(policy.get('restart_on_success', False)))}, "
                f"{int(policy['max_restart_attempts'])}, {int(policy['restart_delay_ms'])}, "
                f"{{{deps[0]}, {deps[1]}, {deps[2]}}}, {dep_count}}},\n"
            )
        out.write("};\n")


def main() -> int:
    if len(sys.argv) == 3 and sys.argv[1] == "--sources":
        services, programs, apps = resolve_product(sys.argv[2])
        for app in apps:
            kind = "services" if app in services else "programs"
            source = Path(kind) / app / "main.cpp"
            if not (REPO_ROOT / source).is_file():
                source = Path("userspace") / app / "main.cpp"
            if not (REPO_ROOT / source).is_file():
                raise RuntimeError(f"missing source for application {app}")
            print(f"{app}:{source}")
        return 0
    if len(sys.argv) != 4:
        print(
            "Usage: generate_product_headers.py <embedded_header> <init_config_header> <product>",
            file=sys.stderr,
        )
        return 1

    embedded_header = Path(sys.argv[1])
    init_config_header = Path(sys.argv[2])
    product_name = sys.argv[3]

    try:
        services, programs, apps = resolve_product(product_name)
        write_embedded_header(embedded_header, apps)
        write_init_config_header(init_config_header, services, programs)
    except Exception as error:  # noqa: BLE001
        print(f"error: {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
